### ISSUE TITLE
Oops! the connection queue is full!

### ISSUE THREAD

**Issue by uaalto** [getlantern/http-proxy#45]
This error happens under load.

**Comment by uaalto** [comment]
This issue is triggered when running many Co Ad tests.

**Comment by fffw** [comment]
So sometimes the queue is filled but never extracted out because the handler has no chance to run, that's really bad. We can remove items from queue when `ConnState` changes, but hope we can find better approach.

**Comment by fffw** [comment]
One way to eliminate the ugly queue is to use goroutine local storage. https://github.com/jtolds/gls provides the feature with a not user friendly API, while https://github.com/tylerb/gls depends on Go's implementation detail, but with nicer API and more efficient.

I'd prefer the latter as we have test as safe net in case the Go implementation changes.

**Comment by fffw** [comment]
https://github.com/tylerb/gls is basically the samething as https://github.com/gorilla/context, except the key is goroutine id, rather than *http.Request. We can't safely assume connection handling and http handler running in same goroutine with the upcoming http2, so it's probably better to just use an mutex protected addr -> connection map.
